// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnnualSalesTable: typeof import('./src/components/annual-sales-table.vue')['default']
    ChannelGrowthPotentialChart: typeof import('./src/components/channelGrowthPotentialChart.vue')['default']
    CustomTable: typeof import('./src/components/customTable.vue')['default']
    CustomTable2: typeof import('./src/components/customTable2.vue')['default']
    ListCard1: typeof import('./src/components/listCard1.vue')['default']
    ListCard2: typeof import('./src/components/listCard2.vue')['default']
    ListLoad: typeof import('./src/components/listLoad.vue')['default']
    MonthSalesChart: typeof import('./src/components/monthSalesChart.vue')['default']
    PageFooter: typeof import('./src/components/pageFooter.vue')['default']
    PageHeader: typeof import('./src/components/pageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenModel: typeof import('./src/components/screenModel.vue')['default']
    SelectUserPrivileges: typeof import('./src/components/selectUserPrivileges.vue')['default']
    ToolTip: typeof import('./src/components/toolTip.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanEmpty: typeof import('vant/es')['Empty']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
